Clarify where `convox run` processes are run
convox/convox pull request #317
Opened 2020-12-10 19:22 UTC by makusu2

It wasn't entirely clear to me whether `convox run` would run the command on the user's local machine using the Convox release's build's image, or on one of their Convox pods. Even digging into the link to the process page (https://docs.convox.com/reference/primitives/app/process) doesn't easily answer the question.

Add a quick note mentioning that the process is run remotely.

2020-12-10 19:22 UTC, makusu2 commented on docs/management/run.md
> +    root@web#
:mag: 

Yeah idk what this change is about :shrug:

2020-12-18 18:05 UTC, makusu2 commented
![image](https://user-images.githubusercontent.com/25968054/102646190-a2796600-4131-11eb-9b5b-d4d43f318a55.png)
I'm pretty sure this is just broken :eyes:

2021-02-02 14:32 UTC, beastawakens requested changes

2021-02-02 14:32 UTC, beastawakens commented on docs/management/run.md
> +[Service](../reference/primitives/app/service.md) on a Convox node and run your command inside the new Process.
```suggestion
[Service](../reference/primitives/app/service.md) on your current Rack and run your command inside the new Process.
```

2021-02-02 16:31 UTC, beastawakens approved these changes

2021-02-02 16:39 UTC, merged