Adding 18.04 support clause.
convox/convox pull request #346
Opened 2021-06-23 17:23 UTC by jasontclark

Addresses: https://trello.com/c/R2uNQERm

Adding the Ubuntu 18.04 support clause to the documentation.

2021-06-23 20:23 UTC, codelitt requested changes

2021-06-23 20:23 UTC, codelitt commented on docs/installation/development-rack/ubuntu.md
> +> **_NOTE:_**:  Currently, we guarantee support for Ubuntu up to version 18.04. Newer versions of Ubuntu have yet to be fully supported.
Let's clarify that support for 20.04 is coming - a wip.

2021-06-24 12:12 UTC, codelitt approved these changes

2021-06-24 12:18 UTC, beastawakens approved these changes

2021-06-24 12:18 UTC, merged