docs: adding copy for ubuntu 20.04 workaround.
convox/convox pull request #362
Opened 2021-07-15 18:05 UTC by jasontclark

Signed-off-by: Jay Clark <jay@convox.com>

2021-07-15 18:17 UTC, kaiomagalhaes approved these changes

2021-07-15 18:28 UTC, beastawakens requested changes

2021-07-15 18:28 UTC, beastawakens commented on docs/installation/development-rack/ubuntu.md
> +> **_NOTE:_**:  Ubuntu 20.04 users will need ensure that they are installing the latest version of convox. See more 'Tips' sections below for more details.
```suggestion
> **_NOTE:_**:  Ubuntu 20.04 users will need to ensure that they are installing the latest version of convox. See more 'Tips' sections below for more details.
```

2021-07-15 18:28 UTC, beastawakens commented on docs/installation/development-rack/ubuntu.md
> +As an Ubuntu 20.04 user, in order to get the Kubernetes steps that follow to work, a slight modification to your local `/etc/resolv.conf` file is required. `microk8s` leverages your local DNS configu
```suggestion
As an Ubuntu 20.04 user, in order to get the Kubernetes steps that follow to work, a slight modification to your local `/etc/resolv.conf` file is required. `microk8s` leverages your local DNS configuration to configure DNS resolution in Kubernetes, and the following commands will provide a workaround to a bug that is encountered with microk8s version 1.13:
```

2021-07-15 18:28 UTC, beastawakens commented on docs/installation/development-rack/ubuntu.md
> +  $ iptables -P FORWARD ACCEPT
```suggestion
    $ iptables -P FORWARD ACCEPT
```

2021-07-15 18:32 UTC, jasontclark commented on docs/installation/development-rack/ubuntu.md
> +> **_NOTE:_**:  Ubuntu 20.04 users will need ensure that they are installing the latest version of convox. See more 'Tips' sections below for more details.
👍

2021-07-15 18:33 UTC, jasontclark commented on docs/installation/development-rack/ubuntu.md
> +As an Ubuntu 20.04 user, in order to get the Kubernetes steps that follow to work, a slight modification to your local `/etc/resolv.conf` file is required. `microk8s` leverages your local DNS configu
👍

2021-07-15 18:33 UTC, jasontclark commented on docs/installation/development-rack/ubuntu.md
> +  $ iptables -P FORWARD ACCEPT
👍

2021-07-16 13:20 UTC, beastawakens submitted a review, later dismissed
:shipit:

2021-07-20 14:07 UTC, ddoc commented on docs/installation/development-rack/ubuntu.md
> +> **_NOTE:_**:  Ubuntu 20.04 users will need ensure that they are installing the latest version of convox. See more 'Tips' sections below for more details.
Capitalize Convox Please

2021-07-20 17:38 UTC, beastawakens approved these changes
:shipit:

2021-07-20 20:32 UTC, merged