Creation of rack using existing VPC and subnet
convox/convox pull request #604
Opened 2023-03-31 01:02 UTC by lucasmacedot

### What is the feature/fix?

** Describe the task and what is the goal for it. **
Currently there's no way to create a rack using an existing VPC and existing subnets
So, the goal with this PR a install of a new cluster, specifying the VPC and subnets to deploy  the cluster

```
convox rack install aws convox-staging \
  vpc_id=vpc-foo123 \
  private_subnets_ids=subnet-foo123,subnet-foo123,subnet-foo123 \
  public_subnets_ids=subnet-foo123,subnet-foo123,subnet-foo123 \
  internet_gateway_id=igw-foo123 \
  region=ap-southeast-2
```

** Describe the bug and the solution. **
** Any additional information **

### Add screenshot or video (optional)

** Any screenshot or video capture using the feature **

### Does it has a breaking change?

** Describe the changes and if it has any breaking changes in any feature **

### How to use/test it?

** Describe how to test or use the feature **

### Checklist
- [ ] New coverage tests
- [ ] Unit tests passing
- [ ] E2E tests passing
- [ ] E2E downgrade/update test passing
- [x] Documentation updated
- [ ] No warnings or errors on Deepsource/Codecov

2023-04-10 15:30 UTC, Twsouza requested changes

2023-04-10 15:30 UTC, Twsouza commented on docs/reference/cli/rack.md
> +url: /reference/cli/rack ---
could you keep `---` in a new line plz?

2023-05-09 03:27 UTC, rickyrattlesnake commented
Hey @nightfury1204 @Twsouza , any updates on this feature going into the next release ?

2023-05-19 17:38 UTC, Twsouza commented
@rickyrattlesnake @lucasmacedot the CI is giving an error on installation:

```
Error: Duplicate resource "null_resource" configuration

  on .terraform/modules/system/terraform/system/aws/main.tf line 82:
  82: resource "null_resource" "wait_for_cluster" {

A null_resource resource named "wait_for_cluster" was already declared at
.terraform/modules/system/terraform/system/aws/main.tf:76,1-44. Resource
names must be unique per type in each module.
```

could you guys please take a look?

2023-05-25 00:39 UTC, lucasmacedot commented
> @rickyrattlesnake @lucasmacedot the CI is giving an error on installation:
> 
> ```
> Error: Duplicate resource "null_resource" configuration
> 
>   on .terraform/modules/system/terraform/system/aws/main.tf line 82:
>   82: resource "null_resource" "wait_for_cluster" {
> 
> A null_resource resource named "wait_for_cluster" was already declared at
> .terraform/modules/system/terraform/system/aws/main.tf:76,1-44. Resource
> names must be unique per type in each module.
> ```
> 
> could you guys please take a look?

Hello
Just fixed it

2023-06-05 17:41 UTC, Twsouza commented
@lucasmacedot  still having error: 

```
Error: Duplicate variable declaration

  on .terraform/modules/system/terraform/system/aws/variables.tf line 196:
 196: variable "private_subnets_ids" {

A variable named "private_subnets_ids" was already declared at
.terraform/modules/system/terraform/system/aws/variables.tf:186,1-31.
Variable names must be unique within a module.


Error: Duplicate variable declaration

  on .terraform/modules/system/terraform/system/aws/variables.tf line 201:
 201: variable "public_subnets_ids" {

A variable named "public_subnets_ids" was already declared at
.terraform/modules/system/terraform/system/aws/variables.tf:191,1-30.
Variable names must be unique within a module.
```

2023-06-07 00:16 UTC, lucasmacedot commented
> @lucasmacedot still having error:
> 
> ```
> Error: Duplicate variable declaration
> 
>   on .terraform/modules/system/terraform/system/aws/variables.tf line 196:
>  196: variable "private_subnets_ids" {
> 
> A variable named "private_subnets_ids" was already declared at
> .terraform/modules/system/terraform/system/aws/variables.tf:186,1-31.
> Variable names must be unique within a module.
> 
> 
> Error: Duplicate variable declaration
> 
>   on .terraform/modules/system/terraform/system/aws/variables.tf line 201:
>  201: variable "public_subnets_ids" {
> 
> A variable named "public_subnets_ids" was already declared at
> .terraform/modules/system/terraform/system/aws/variables.tf:191,1-30.
> Variable names must be unique within a module.
> ```

Fixed, sorry, that happened when I had to rebase staging

2023-06-20 23:46 UTC, RaphaelMacedonio commented
Hello @Twsouza and @nightfury1204, do we need to change anything else here for this PR to be merged and then released? What are the next steps? Is the anything that @lucasmacedot and I can help with? 
thanks.

2023-06-21 10:05 UTC, nightfury1204 commented
@lucasmacedot @RaphaelMacedonio thanks I will run ci again

2023-06-21 10:50 UTC, nightfury1204 commented
Based on the hight availability  we have to consider the implementation. for example when high availability is enabled it expects 3 subnets in three az
I don't think this implementation has consider that

2023-06-23 01:48 UTC, lucasmacedot commented
> Based on the hight availability we have to consider the implementation. for example when high availability is enabled it expects 3 subnets in three az. And there might be other edge cases I don't think this implementation has consider that

The scenario you are talkng about is that:
If I pass only 1 subnet, and HA is enabled, terraform should create 2 more subnets?

2023-06-23 15:14 UTC, nightfury1204 commented
> > Based on the hight availability we have to consider the implementation. for example when high availability is enabled it expects 3 subnets in three az. And there might be other edge cases I don't think this implementation has consider that
> 
> The scenario you are talkng about is that: If I pass only 1 subnet, and HA is enabled, terraform should create 2 more subnets?

it shouldn't create other 2 (it can but it will have complicated logic to figure out the subnet). In HA, it expects 3 subnets in 3 az, if we provide manually it should consider that and also in HA we expect 3 nat gateway. If you go through the code you will find out there are coupling logic around that

2023-07-18 23:59 UTC, RaphaelMacedonio commented
Hey team, @lucasmacedot @rickyrattlesnake @nightfury1204 @Twsouza is there a better way on integrating this feature? Shall we pair somehow or get a quick call to discuss and understand the better way on moving with this?

2023-07-19 11:19 UTC, nightfury1204 commented
Hey @lucasmacedot @RaphaelMacedonio I still haven't got time to review it. Let me go through it. I will let you guys know
thanks

2023-08-01 23:43 UTC, nightfury1204 commented
@lucasmacedot can you squash the commits and rebase this branch with `staging`?

2023-08-02 04:31 UTC, lucasmacedot commented
Hello @nightfury1204 When I created this PR I created it based on the main branch, but I was asked to rebase to staging, but at the time there were differences between the main branch and the staging branch, and this messed up the history of the branch, that's why there're rebase conflicts everytime there's a change on staging
I just created a new branch based on staging from the beginning, so these rebase problems don't happen anymore

It's in this PR: https://github.com/convox/convox/pull/677

2023-08-02 04:31 UTC, closed without merging